name: Claude Code Helper

on:
  issues:
    types: [opened]

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  run-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Claude Code Action Official
        uses: anthropics/claude-code-action@beta